name: code_style

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    container: ubuntu:24.04

    steps:
      - uses: actions/checkout@v3
      - name: Run linters
        run: |
          apt update -y
          apt install -y make clang-format
          make lint
